### PR TITLE
Add option to prefix metric names with job+index

### PR DESCRIPTION
**Pull request by dcarley**
Which prepends the CloudFoundry job name (e.g. `runner_z1`) and job index
(e.g. `0`) to every metric name. We want this in order to debug issues with
particular servers, for example if Doppler is sending messages on one side
but they aren't all being received on the other end.

The way that this option is passed through is sub-optimal. We did consider
some other options like whether we could change the prefix of the statsd
client on the fly, but it wasn't possible/efficient. The codebase could
benefit from some refactoring, to reduce duplication.

To use this you will need to run something like:

    cf set-env graphite-nozzle PREFIX_JOB true

---

Is this useful to other users? Should it be the default?

### CODE REVIEW

**Comment by teddyking** [comment]
Hi there,

Thanks for the PR! This definitely looks like it would be very useful.
I'll take a look when I get a spare moment and hopefully merge this in.

As for whether or not this should be the default, I don't have a particularly strong preference either way. What would be best for you/others?

**Comment by dcarley** [comment]
We'd would prefer for it to be the default. I recognise it'll be disruptive for existing users though; they'll need to set the environment variable when they upgrade. Semantic versioning and release notes could make that easier though.

Please let me know if you have any thoughts or suggestions on the actual code or naming.

**Comment by teddyking** [comment]
Sorry for taking so long to get back to you on this.
That's a good point about not wanting to disrupt existing users.
Perhaps we could not make it the default at the moment, but when I get around to releasing a semantically-versioned release we could set it to the default then?
I've been working on a pipeline in the `ci-wip` branch to help get this all setup.

**Comment by saliceti** [comment]
Hi Teddy, any update on this PR?

**Comment by teddyking** [comment]
Hey @saliceti - sorry for the delay in getting back to you on this.
PR all looks good to me, merging now.

Thanks!

**Comment by dcarley** [comment]
Thanks!

**Comment by saliceti** [comment]
Cheers

**Pull request merged**
