### PR TITLE
New deps, auth token lib, debug, parse cmd line.

### PR DESCRIPTION
**Pull request by simonjohansson**
Update deps, add library for dealing for auth tokens, parse commandline, enable debug printing.

### CODE REVIEW

**Comment by teddyking** [comment]
This looks great! And also looks like a suitable solution to [https://github.com/CloudCredo/graphite-nozzle/issues/3](https://github.com/CloudCredo/graphite-nozzle/issues/3) (@bonzofenix and @cloud-dude - would you care to comment?).

I'm getting a `Received a status code 401 Unauthorized` error message when trying to run it. My admin user has the correct scopes, and running the previous nozzle against the same bosh-lite CF seems to work fine. Is there something I'm missing?

**Comment by simonjohansson** [comment]
@teddyking ah yes, forgot to update the docs about that.

This PR makes the assumption that a client have been added to the installation like, https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle#configure-cloudfoundry-uaa-for-firehose-nozzle

I can alter the PR to use the go-cfclient if you would rather login with a normal user like we do in firehose-to-syslog.

**Comment by teddyking** [comment]
Ah that'd be it.
Let's keep it as it is and update the docs - it probably makes sense to keep in line with what other nozzle authors are doing.

**Comment by simonjohansson** [comment]
@teddyking agreed, to some extent, makes it harder to test against bosh-lite as you have to remember to create a firehose user in the manifest though.

Maybe we can suggest to the Pivotal foks to have a default firehose user in the templates?

**Comment by teddyking** [comment]
Looks great - all merged. Thanks for the PR!
And yeah I think it'd be really useful to have a default firehose user in the templates.

**Pull request merged**
